WIDTH = 1000
HEIGHT = 600
FPS = 100
TEXT_SIZE_REL = 0.01
LABEL_COLOR = (0, 0, 0)
BUTTON_COLOR = (0, 0, 0)
MARIGIN_PERC = 0.02
CARD_SPACE_HEIGHT_PERC = 0.14
DEFAULT_TEXT_SIZE = 10

# GAMEPLAY SETTINGS
PICK_SPACE_VISIBILITY = True
TRASH_SPACE_VISIBILITY = True
LOOT_SPACE_VISIBILITY = True